DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_roles WHERE rolname='__JMETER_DB_USER__') THEN 
        CREATE ROLE __JMETER_DB_USER__ WITH LOGIN PASSWORD '__JMETER_DB_PASSWORD__';
        GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO __JMETER_DB_USER__;
        GRANT ALL PRIVILEGES ON DATABASE jmeter TO __JMETER_DB_USER__;
        GRANT ALL PRIVILEGES ON DATABASE grafana TO __JMETER_DB_USER__;
        GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO __JMETER_DB_USER__;
        ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO __JMETER_DB_USER__;
        ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO __JMETER_DB_USER__;
    END IF;

    IF NOT EXISTS(SELECT 1 FROM pg_roles WHERE rolname='__GRAFANA_DB_USER__') THEN 
        CREATE ROLE __GRAFANA_DB_USER__ WITH LOGIN PASSWORD '__GRAFANA_DB_PASSWORD__';
        GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO __GRAFANA_DB_USER__;
        GRANT ALL PRIVILEGES ON DATABASE grafana TO __GRAFANA_DB_USER__;
        GRANT ALL PRIVILEGES ON DATABASE jmeter TO __GRAFANA_DB_USER__;
        GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO __GRAFANA_DB_USER__;
        ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO __GRAFANA_DB_USER__;
        ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO __GRAFANA_DB_USER__;
    END IF;
END;
$$ LANGUAGE plpgsql;